name: CI

on:
  push:
    branches:
      - "[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]/rc"
  pull_request:
    branches:
      - develop

jobs:
  ci:
    uses: mssfoobar/.github/.github/workflows/npm-ci.yml@main
    with:
      node-version: "24"
      legacy-peer-deps: true
